/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author mzuleta4
 */
public class VectorUno extends javax.swing.JFrame {

    /**
     * Creates new form VectorUno
     */
    double v[];
    double acum, mul;
    double men, may;

    public VectorUno() {
        initComponents();
        
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(false);
        cmdMostrarTodo.setEnabled(false);
        txtL.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtL = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoM = new javax.swing.JButton();
        cmdLlenadoA = new javax.swing.JButton();
        cmdMostrarM = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdMostrarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Multifuncional");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Vector Multifuncional");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Iniciales", 2, 0, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Longitud");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLKeyTyped(evt);
            }
        });
        jPanel4.add(txtL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 90, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", 2, 0, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        cmdLlenadoM.setText("Llenado Manual");
        cmdLlenadoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoMActionPerformed(evt);
            }
        });
        cmdLlenadoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdLlenadoMKeyTyped(evt);
            }
        });
        jPanel3.add(cmdLlenadoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, -1));

        cmdLlenadoA.setText("Llenado Automatico");
        cmdLlenadoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenadoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        cmdMostrarM.setText("Núm. Mayor y Menor");
        cmdMostrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarMActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 150, -1));

        cmdMostrarTodo.setText("Mostrar Todo");
        cmdMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarTodoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 170, 340));

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtR.setRows(5);
        txtR.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jScrollPane1.setViewportView(txtR);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        setSize(new java.awt.Dimension(599, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }

    }//GEN-LAST:event_txtLKeyTyped

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed

        int L;

        if (txtL.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
        } else if (Integer.parseInt(txtL.getText().trim()) == 0){
            JOptionPane.showMessageDialog(this, "Digite Una Longitud Superior A 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtL.requestFocusInWindow();
            txtL.selectAll();
        } else {

            L = Integer.parseInt(txtL.getText());
            v = new double[L];
            JOptionPane.showMessageDialog(this, "Vector Creado Satisfatoriamente");
            txtL.setText("");

            cmdCrear.setEnabled(false);
            cmdLlenadoM.setEnabled(true);
            cmdLlenadoA.setEnabled(true);
            cmdMostrarM.setEnabled(false);
            cmdMostrarTodo.setEnabled(false);
            cmdBorrar.setEnabled(true);
            txtL.setEditable(false);

        }

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoMActionPerformed

        double n;
        acum = 0;
        mul = 1;

        
        for (int i = 0; i < v.length; i++) {
            
        
            n = Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento de la posicion " + i));
            
            v[i] = n;
            acum = acum + v[i];
            mul = mul * v[i];

        }
        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        for (int i = 0; i < v.length; i++) {

            if (i == 0) {

                may = v[0];
                men = v[0];

            }
            if (v[i] > may) {
                may = v[i];
            }
            if (v[i] < men) {
                men = v[i];
            }

        }

        cmdCrear.setEnabled(false);
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(true);
        cmdMostrarTodo.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);

    }//GEN-LAST:event_cmdLlenadoMActionPerformed

    private void cmdLlenadoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAActionPerformed

        double n;

        acum = 0;
        mul = 1;
        for (int i = 0; i < v.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v[i] = n;
            acum = acum + v[i];
            mul = mul * v[i];

        }

        for (int i = 0; i < v.length; i++) {
            if (i == 0) {

                may = v[0];
                men = v[0];

            }
            if (v[i] > may) {
                may = v[i];
            }
            if (v[i] < men) {
                men = v[i];
            }

        }

        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear.setEnabled(false);
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(true);
        cmdMostrarTodo.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);
    }//GEN-LAST:event_cmdLlenadoAActionPerformed

    private void cmdMostrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarMActionPerformed

        txtR.setText("");
        txtR.append("El Número Mayor Es: " + may + "\nEl Número Menor es: " + men);

        cmdCrear.setEnabled(false);
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(true);
        cmdMostrarTodo.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);

    }//GEN-LAST:event_cmdMostrarMActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed

        txtL.setText("");
        txtR.setText("");
        txtL.requestFocusInWindow();
        v = null;

        cmdCrear.setEnabled(true);
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(false);
        cmdMostrarTodo.setEnabled(false);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(true);

    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarTodoActionPerformed

        txtR.setText("");

        txtR.append("La Sumatoria es: " + acum + "\nLa Productoria es: " + mul
                + "\nEl Número Mayor Es: " + may + "\nEl Número Menor es: " + men);

        cmdCrear.setEnabled(false);
        cmdLlenadoM.setEnabled(false);
        cmdLlenadoA.setEnabled(false);
        cmdMostrarM.setEnabled(true);
        cmdMostrarTodo.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtL.setEditable(false);

    }//GEN-LAST:event_cmdMostrarTodoActionPerformed

    private void cmdLlenadoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdLlenadoMKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_cmdLlenadoMKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VectorUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VectorUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VectorUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VectorUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VectorUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenadoA;
    private javax.swing.JButton cmdLlenadoM;
    private javax.swing.JButton cmdMostrarM;
    private javax.swing.JButton cmdMostrarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
